"""
Documentation generation endpoints.
"""
import time
import logging
import warnings
from datetime import datetime, timedelta, timezone
from typing import List, Optional, Dict, Any
from fastapi import APIRouter, HTTPException, status

# Suppress SSL warnings for internal GitLab
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
warnings.filterwarnings("ignore", message="Unverified HTTPS request")

from ..deps import ApiKeyDep
from ..schemas import (
    DocumentationRequest,
    DocumentationResponse,
    HistoryEventResponse
)

logger = logging.getLogger(__name__)

router = APIRouter(
    prefix="/documentation",
    tags=["📄 Документация"]
)


@router.post(
    "/generate",
    response_model=DocumentationResponse,
    summary="Генерация API документации",
    description="""
Генерирует документацию для OpenAPI эндпоинта из предварительно вычисленной истории в кеше.

**Процесс:**
1. Читает историю изменений из кеша (быстро!)
2. Публикует документацию в Confluence

**Предварительные требования:** Сначала запустите `/cache/warm` для заполнения кеша.

> ⚠️ Возвращает 404, если история эндпоинта отсутствует в кеше (Strict Cache Mode).
    """
)
async def generate_documentation(
    request: DocumentationRequest,
    api_key: ApiKeyDep
) -> DocumentationResponse:
    """Генерация документации из предварительно вычисленной истории (Strict Cache)."""
    start_time = time.time()
    
    try:
        # Parse target endpoint
        parts = request.target_endpoint.split(" ", 1)
        if len(parts) != 2:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Invalid target_endpoint format. Expected 'METHOD /path', got: {request.target_endpoint}"
            )
        
        method, path = parts[0].upper(), parts[1]
        endpoint_key = f"{method} {path}"
        
        # Try to get pre-computed history
        from src.cache.disk_cache import DiskCacheManager
        from src.cache.endpoint_history_cache import EndpointHistoryCache
        
        cache = DiskCacheManager()
        history_cache = EndpointHistoryCache(cache)
        
        history = history_cache.get_history(request.project_path, endpoint_key)
        
        if history and history.events:
            logger.info(f"[GENERATE] Using pre-computed history: {len(history.events)} events")
            
            # Convert to legacy format for publisher
            # IMPORTANT: Use event.diff from cache directly instead of recalculating!
            # Recalculating was causing cosmetic changes to be filtered out prematurely.
            history_events = []
            for event in history.events:
                history_events.append({
                    'date': event.merged_at[:10] if event.merged_at else '',
                    'task_id': event.task_id,
                    'mr_id': event.mr_iid,
                    'author': event.author,
                    'type': f"{'🆕 ' if event.event_type == 'CREATED' else '📝 ' if event.event_type == 'MODIFIED' else '❌ '}{event.event_type}",
                    'changes': '',  # Will be generated by confluence_template_generator from diff
                    'diff': event.diff,  # Use cached diff directly!
                    'schema': event.schema,
                    'previous_schema': event.previous_schema,
                    'field_changes': event.field_changes,
                    'link': event.mr_link,
                    'jira_link': event.jira_link,
                })
            
            cache.close()
        else:
            cache.close()
            error_msg = f"Endpoint '{endpoint_key}' not found in cache. Please run /cache/warm first."
            logger.warning(f"[GENERATE] {error_msg}")
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=error_msg
            )
        
        # Publish to Confluence
        from config import settings
        from src.confluence.publisher import ConfluencePublisher
        
        publisher = ConfluencePublisher(
            base_url=settings.confluence_base_url,
            token=request.confluence_token or settings.confluence_token,
            space_key=request.confluence_space_key or settings.confluence_space_key,
            parent_page_id=request.confluence_parent_page_id
        )
        
        result = publisher.publish_history(
            method=method,
            path=path,
            events=history_events,
            project_path=request.project_path
        )
        
        processing_time = time.time() - start_time
        
        # Convert events to response format
        events_to_return = result.get('events', history_events)
        
        events_response = []
        for evt in events_to_return:
            events_response.append(HistoryEventResponse(
                event_type=evt.get('event_type', evt.get('type', '')).replace("🆕 ", "").replace("📝 ", "").replace("❌ ", ""),
                task_id=evt['task_id'],
                mr_iid=evt.get('mr_iid', evt.get('mr_id', 0)),
                author=evt['author'],
                merged_at=evt.get('merged_at', evt.get('date')),
                field_changes=evt.get('field_changes')
            ))
        
        logger.info(f"[GENERATE] Complete in {processing_time:.2f}s")
        
        return DocumentationResponse(
            success=result.get("success", False),
            page_id=result.get("page_id"),
            page_url=result.get("page_url"),
            events_count=len(events_to_return),
            processing_time_sec=round(processing_time, 2),
            events=events_response if len(events_response) <= 20 else None,
            error=None if result.get("success") else "Failed to publish to Confluence"
        )
            
    except HTTPException:
        raise
    except Exception as e:
        logger.exception(f"[GENERATE] Documentation generation failed: {e}")
        processing_time = time.time() - start_time
        return DocumentationResponse(
            success=False,
            page_id=None,
            page_url=None,
            events_count=0,
            processing_time_sec=round(processing_time, 2),
            events=None,
            error=str(e)
        )


def _normalize_allof_order(schema: dict) -> dict:
    """
    Recursively sort allOf/anyOf/oneOf arrays by their first property key.
    This ensures consistent ordering for comparison regardless of source order.
    Synced with main_turbo.py implementation.
    """
    if not isinstance(schema, dict):
        return schema
    
    result = {}
    for key, value in schema.items():
        if key in ('allOf', 'anyOf', 'oneOf') and isinstance(value, list):
            # Sort array items by first property key (if they have properties)
            def sort_key(item):
                if isinstance(item, dict) and 'properties' in item:
                    props = item['properties']
                    if props:
                        return sorted(props.keys())[0]
                return ''
            
            sorted_items = sorted(value, key=sort_key)
            result[key] = [_normalize_allof_order(item) for item in sorted_items]
        elif isinstance(value, dict):
            result[key] = _normalize_allof_order(value)
        elif isinstance(value, list):
            result[key] = [_normalize_allof_order(item) if isinstance(item, dict) else item for item in value]
        else:
            result[key] = value
    
    return result


def _run_history_builder_with_params(
    target_endpoint: str,
    method: str,
    path: str,
    gitlab_token: Optional[str] = None,
    project_path: Optional[str] = None
) -> List[dict]:
    """
    Run TurboHistoryBuilder with explicit endpoint parameters.
    
    This avoids modifying the global settings object.
    """
    import os
    import shutil
    import re
    from concurrent.futures import ThreadPoolExecutor, as_completed
    from deepdiff import DeepDiff
    
    from config import settings
    from src.processing.regression_filter import RegressionFilter, FieldChange
    
    # Import and create builder
    import gitlab
    from src.cache.disk_cache import DiskCacheManager
    from src.openapi.spec_loader import SpecLoader
    from src.openapi.schema_extractor import SchemaExtractor
    
    # Cosmetic fields to exclude (sync with main_turbo.py)
    EXCLUDE_COSMETIC_FIELDS = [
        # Documentation fields (pure text, no API impact)
        re.compile(r"\['description'\]"),
        re.compile(r"\['summary'\]"),
        re.compile(r"\['title'\]"),
        re.compile(r"\['externalDocs'\]"),
        re.compile(r"\['deprecated'\]"),
        re.compile(r"\['tags'\]"),
        re.compile(r"\['operationId'\]"),
        # Validation hints (don't change API contract)
        re.compile(r"\['minItems'\]"),
        re.compile(r"\['maxItems'\]"),
        re.compile(r"\['minLength'\]"),
        re.compile(r"\['maxLength'\]"),
        re.compile(r"\['minimum'\]"),
        re.compile(r"\['maximum'\]"),
        re.compile(r"\['pattern'\]"),
        re.compile(r"\['default'\]"),
        re.compile(r"\['x-.*'\]"),  # Extension fields
        # Schema attributes that are not contract changes
        re.compile(r"\['example'\]"),  # Example values
        # NOTE: format is NOT excluded - it indicates meaningful changes (uuid vs string)
    ]
    
    # Validate inputs
    token_to_use = gitlab_token or settings.gitlab_token
    if not token_to_use:
        raise ValueError("gitlab_token is required - pass it in request body or set GITLAB_TOKEN in .env")
    
    project_to_use = project_path or settings.project_path
    if not project_to_use:
        raise ValueError("project_path is required - pass it in request body")
    
    # Create a lightweight builder-like object
    gl = gitlab.Gitlab(
        url=settings.gitlab_url,
        private_token=token_to_use,
        ssl_verify=settings.gitlab_ssl_verify
    )
    gl.auth()
    project = gl.projects.get(project_to_use)
    cache = DiskCacheManager()
    
    # Use explicit method and path
    endpoint = target_endpoint
    
    try:
        # Fetch MRs
        mrs_iter = project.mergerequests.list(
            state='merged',
            target_branch='master',
            order_by='merged_at',
            sort='asc',
            iterator=True,
            per_page=100
        )
        
        # Limit number of MRs if configured
        limit = settings.mr_limit or 100
        
        all_mrs = []
        for mr in mrs_iter:
            if len(all_mrs) >= limit:
                break
            if not mr.merge_commit_sha:
                continue
            
            task_id = _extract_task_id(mr.title, mr.source_branch)
            all_mrs.append({
                'mr_iid': mr.iid,
                'commit_sha': mr.merge_commit_sha,
                'date': mr.merged_at,
                'author': mr.author.get('name', 'Unknown') if mr.author else 'Unknown',
                'title': mr.title,
                'source_branch': mr.source_branch,
                'task_id': task_id
            })
        
        # Sort and deduplicate
        sorted_mrs = sorted(all_mrs, key=lambda x: (x['date'][:19], x['mr_iid']))
        
        seen_commits = set()
        deduped_mrs = []
        for mr in sorted_mrs:
            if mr['commit_sha'] not in seen_commits:
                seen_commits.add(mr['commit_sha'])
                deduped_mrs.append(mr)
        
        temp_dir_base = "temp_api"
        if os.path.exists(temp_dir_base):
            shutil.rmtree(temp_dir_base)
        os.makedirs(temp_dir_base)
        
        schemas: Dict[str, Any] = {}
        relevant_mrs = []
        
        # Build endpoint key for cache (same format as main_turbo.py uses)
        endpoint_key = f"{method} {path}"
        
        # Process MRs
        for mr in deduped_mrs:
            commit_sha = mr['commit_sha']
            
            # Check cache first (with project_path)
            cached_schema = cache.get_schema(project_to_use, commit_sha[:8], endpoint_key)
            if cached_schema is not None:
                if cached_schema:  # Not empty dict (which means no endpoint)
                    schemas[commit_sha] = cached_schema
                    relevant_mrs.append(mr)
                continue
            
            # Check spec cache
            cached_spec = cache.get_spec(project_to_use, commit_sha[:16])
            if cached_spec:
                schema = SchemaExtractor.extract(cached_spec, method, path)
                cache.set_schema(project_to_use, commit_sha[:8], endpoint_key, schema or {})
                if schema:
                    schemas[commit_sha] = schema
                    relevant_mrs.append(mr)
                continue
            
            # Need to download
            try:
                temp_dir = os.path.join(temp_dir_base, commit_sha[:8])
                os.makedirs(temp_dir, exist_ok=True)
                
                # Download archive as artifacts.zip (same as main_turbo.py)
                archive_path = os.path.join(temp_dir, "artifacts.zip")
                with open(archive_path, 'wb') as f:
                    project.repository_archive(sha=commit_sha, streamed=True, action=f.write, format='zip')
                
                # Load spec using SpecLoader (handles extraction internally)
                loader = SpecLoader()
                spec = loader.load_spec_from_snapshot(temp_dir)
                if spec:
                    cache.set_spec(project_to_use, commit_sha[:16], spec)
                    schema = SchemaExtractor.extract(spec, method, path)
                    cache.set_schema(project_to_use, commit_sha[:8], endpoint_key, schema or {})
                    if schema:
                        schemas[commit_sha] = schema
                        relevant_mrs.append(mr)
                
                # Cleanup
                shutil.rmtree(temp_dir, ignore_errors=True)
                
            except Exception as e:
                logger.warning(f"Failed to process MR !{mr['mr_iid']}: {e}")
        
        # Compare schemas
        relevant_mrs_sorted = sorted(relevant_mrs, key=lambda x: (x['date'][:19], x['mr_iid']))
        
        history_events = []
        field_changes: List[FieldChange] = []
        previous_schema: Optional[Dict] = None
        
        for mr in relevant_mrs_sorted:
            commit_sha = mr['commit_sha']
            current_schema = schemas.get(commit_sha)
            
            event_type = None
            changes = None
            diff = None
            
            if previous_schema is None and current_schema is not None:
                # Check if it's a Revert that restores the endpoint
                if mr.get('task_id') == 'REVERT' or mr.get('title', '').lower().startswith('revert'):
                     # If we found a task ID in _extract_task_id but it started with Revert,
                     # we might want to flag it as REVERT event but keep the task ID.
                     # But here we rely on what _extract_task_id returned.
                     # If _extract_task_id returned valid task (LOG-5424), we should still mark event as REVERT if title says so.
                     if mr.get('title', '').lower().startswith('revert'):
                         event_type = "REVERT" 
                     else:
                         event_type = "🆕 CREATED"
                     
                else:
                    event_type = "🆕 CREATED"
                changes = "Endpoint Created"
            elif previous_schema is not None and current_schema is None:
                event_type = "❌ DELETED"
                changes = "Endpoint Deleted"
            elif previous_schema is not None and current_schema is not None:
                # Normalize allOf/anyOf/oneOf ordering before comparison
                # This prevents false positives from array element reordering
                normalized_prev = _normalize_allof_order(previous_schema)
                normalized_curr = _normalize_allof_order(current_schema)
                
                # IMPORTANT: Use ignore_order=True but DO NOT exclude cosmetic fields!
                # We want to capture description/example changes so Publisher can handle them (skip them).
                # If we exclude them here, Publisher sees empty diff and treats it as 'Contract changes'.
                diff = DeepDiff(
                    normalized_prev,
                    normalized_curr,
                    ignore_order=True
                )
                if diff:
                    event_type = "📝 MODIFIED"
                    changes = _format_diff(diff)
                    
                    # Collect field changes for regression filtering
                    merged_at = _parse_date(mr['date'])
                    
                    if 'dictionary_item_added' in diff:
                        for path in diff['dictionary_item_added']:
                            field_changes.append(FieldChange(
                                field_path=_normalize_path(path),
                                change_type="added",
                                mr_iid=mr['mr_iid'],
                                merged_at=merged_at,
                                mr_title=mr.get('title', ''),
                                task_id=mr.get('task_id', '')
                            ))
                    
                    if 'dictionary_item_removed' in diff:
                        for path in diff['dictionary_item_removed']:
                            field_changes.append(FieldChange(
                                field_path=_normalize_path(path),
                                change_type="removed",
                                mr_iid=mr['mr_iid'],
                                merged_at=merged_at,
                                mr_title=mr.get('title', ''),
                                task_id=mr.get('task_id', '')
                            ))
            
            if event_type:
                history_events.append({
                    'date': mr['date'][:10],
                    'task_id': mr['task_id'],
                    'mr_id': mr['mr_iid'],
                    'author': mr['author'],
                    'type': event_type,
                    'changes': changes,
                    'diff': diff,
                    'schema': current_schema,
                    'previous_schema': previous_schema,
                    'link': f"{settings.gitlab_url}/{settings.project_path}/-/merge_requests/{mr['mr_iid']}",
                    'jira_link': f"{settings.jira_base_url}/{mr['task_id']}" if mr['task_id'] != 'NO-TASK' else None
                })
            
            previous_schema = current_schema
        
        logger.info(f"[API] Phase 2 complete: {len(history_events)} events before filtering")
        for e in history_events:
            logger.info(f"  [API] {e['task_id']} - {e['type']}")
        
        # Phase 3: Filter temporary regressions
        if settings.filter_temporary_regressions and field_changes:
            regression_filter = RegressionFilter(
                grace_period_days=settings.grace_period_days,
                min_regression_duration_hours=settings.min_regression_duration_hours
            )
            filter_result = regression_filter.filter_events(field_changes)
            
            if filter_result.temporary_regressions:
                logger.info(f"Found {len(filter_result.temporary_regressions)} temporary regressions to filter")
                # Filter out events that are part of temporary regressions
                history_events = _filter_regression_events(history_events, filter_result.temporary_regressions)
        
        logger.info(f"[API] After regression filter: {len(history_events)} events")
        for e in history_events:
            logger.info(f"  [API] {e['task_id']} - {e['type']}")
        
        # Phase 4: Filter REVERT pairs (DELETED → CREATED within grace period)
        history_events = _filter_revert_pairs(history_events, settings.grace_period_days)
        
        logger.info(f"[API] After REVERT filter: {len(history_events)} events")
        for e in history_events:
            logger.info(f"  [API] {e['task_id']} - {e['type']}")
        
        return history_events
        
    finally:
        cache.close()
        if temp_dir_base and os.path.exists(temp_dir_base):
            shutil.rmtree(temp_dir_base, ignore_errors=True)


def _extract_task_id(title: str, branch: str) -> str:
    """
    Extract JIRA task ID from MR title or branch.
    
    Handles various formats:
    - LOGRETAIL-1168, LOG-4996 (standard JIRA)
    - logretail-1168 (lowercase)
    - logretail 1168 (space separator)
    - feature/LOGRETAIL-1168 (in branch path)
    
    Returns normalized format: PROJECT-NUMBER (uppercase) or REVERT or NO-TASK
    """
    import re
    
    # Combine sources for searching (title first, then branch)
    sources = [title, branch]
    
    for text in sources:
        if not text:
            continue
            
        # Pattern 1: Standard JIRA format (PROJ-123, at least 2 letters, 1+ digits)
        match = re.search(r'([A-Z]{2,})-(\d+)', text, re.IGNORECASE)
        if match:
            return f"{match.group(1).upper()}-{match.group(2)}"
        
        # Pattern 2: Alternative separators (PROJ_123, PROJ 123, PROJ/123)
        match = re.search(r'([A-Z]{2,})[\s_/](\d+)', text, re.IGNORECASE)
        if match:
            return f"{match.group(1).upper()}-{match.group(2)}"

    # Check for REVERT (Fallback if no task ID found)
    if title.lower().startswith('revert') or branch.lower().startswith('revert'):
        return 'REVERT'
    
    return 'NO-TASK'


def _format_diff(diff) -> str:
    """Format DeepDiff for display."""
    lines = []
    if 'dictionary_item_added' in diff:
        for item in diff['dictionary_item_added']:
            path = item.replace("root", "")
            lines.append(f"Added: **{path}**")
    if 'dictionary_item_removed' in diff:
        for item in diff['dictionary_item_removed']:
            path = item.replace("root", "")
            lines.append(f"Removed: **{path}**")
    if 'values_changed' in diff:
        for key in diff['values_changed']:
            path = key.replace("root", "")
            lines.append(f"Changed **{path}**")
    
    if len(lines) > 5:
        lines = lines[:5] + [f"*(+{len(lines)-5} more)*"]
    return "<br>".join(lines) if lines else "Minor changes"


def _parse_date(date_str: str) -> datetime:
    """Parse ISO date string to datetime."""
    from datetime import datetime, timezone
    
    if not date_str:
        return datetime.now(timezone.utc)
    
    # Handle various ISO formats
    date_str = date_str.replace('Z', '+00:00')
    try:
        return datetime.fromisoformat(date_str)
    except ValueError:
        # Fallback: try parsing without timezone
        try:
            dt = datetime.fromisoformat(date_str[:19])
            return dt.replace(tzinfo=timezone.utc)
        except ValueError:
            return datetime.now(timezone.utc)


def _normalize_path(path: str) -> str:
    """Normalize DeepDiff path for comparison."""
    import re
    # Remove 'root' prefix and normalize brackets
    path = path.replace("root", "")
    # Normalize array indices like [0] to [*]
    path = re.sub(r'\[\d+\]', '[*]', path)
    return path


def _filter_regression_events(
    events: List[dict],
    temporary_regressions: List
) -> List[dict]:
    """
    Filter out events that are part of temporary regressions.
    
    A temporary regression is when a field is removed and then restored
    within the grace period. Both the removal and restoration events
    should be filtered out.
    """
    if not temporary_regressions:
        return events
    
    # Build set of (mr_iid) that should be filtered
    # We filter MODIFIED events from MRs that are part of regressions
    regression_mr_iids = set()
    for reg in temporary_regressions:
        regression_mr_iids.add(reg.deleted_in_mr)
        regression_mr_iids.add(reg.restored_in_mr)
    
    logger.info(f"Filtering events from MRs: {regression_mr_iids}")
    
    # Filter events, but only MODIFIED ones (keep CREATED/DELETED)
    filtered = []
    for event in events:
        if event['mr_id'] in regression_mr_iids and '📝 MODIFIED' in event['type']:
            logger.info(f"  Filtered regression event: !{event['mr_id']} ({event['task_id']})")
            continue
        filtered.append(event)
    
    return filtered


def _filter_revert_pairs(events: List[dict], grace_period_days: int = 7) -> List[dict]:
    """
    Filter out REVERT pairs: DELETED → CREATED within grace period.
    
    Pattern: A REVERT MR deletes endpoint, then another REVERT restores it.
    If both happen within grace_period_days, filter out both events.
    """
    from datetime import datetime, timedelta
    
    if not events:
        return events
    
    # Find DELETED events from REVERT MRs
    deleted_indices = []
    for i, e in enumerate(events):
        if e['task_id'] == 'REVERT' and '❌ DELETED' in e['type']:
            deleted_indices.append(i)
    
    if not deleted_indices:
        return events
    
    # For each DELETED, look for matching CREATED within grace period
    pairs_to_remove = set()
    grace_period = timedelta(days=grace_period_days)
    
    for del_idx in deleted_indices:
        del_event = events[del_idx]
        del_date = datetime.fromisoformat(del_event['date'])
        
        # Look for CREATED after this DELETED
        for i in range(del_idx + 1, len(events)):
            evt = events[i]
            if '🆕 CREATED' in evt['type']:
                evt_date = datetime.fromisoformat(evt['date'])
                if evt_date - del_date <= grace_period:
                    # Found a pair - mark both for removal
                    pairs_to_remove.add(del_idx)
                    pairs_to_remove.add(i)
                    logger.info(f"Filtered REVERT pair: !{del_event['mr_id']} (DELETED) + !{evt['mr_id']} (CREATED)")
                    break
    
    if pairs_to_remove:
        return [e for i, e in enumerate(events) if i not in pairs_to_remove]
    
    return events
